# Generated by Django 2.2.15 on 2022-09-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('server_id', models.CharField(max_length=10)),
                ('positions', models.BinaryField()),
                ('planets', models.BinaryField()),
            ],
        ),
    ]
