# Generated by Django 2.2.15 on 2022-09-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
