# Generated by Django 2.2.15 on 2022-09-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0003_auto_20220914_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date',
        ),
        migrations.AddField(
            model_name='score',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
