# Generated by Django 2.2.15 on 2022-09-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0004_auto_20220915_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
