# Generated by Django 2.2.15 on 2022-09-23 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0005_player_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=15)),
                ('found_date', models.DateTimeField()),
                ('logo', models.TextField()),
                ('homepage', models.TextField()),
                ('application_open', models.BooleanField()),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogame.Player')),
            ],
        ),
    ]
