# Generated by Django 2.2.15 on 2022-09-23 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0006_alliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='application_open',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='found_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ogame.Player'),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='homepage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='tag',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
