# Generated by Django 2.2.15 on 2022-09-23 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0007_auto_20220923_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_alliance', to='ogame.Alliance'),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founder_player', to='ogame.Player'),
        ),
    ]
