# Generated by Django 2.2.15 on 2022-09-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0008_auto_20220923_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastScorePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('prediction', models.BinaryField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogame.Player')),
            ],
        ),
    ]
