# Generated by Django 2.2.15 on 2022-10-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0009_pastscoreprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='members',
            field=models.ManyToManyField(null=True, related_name='ally_members', to='ogame.Player'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='planets_distribution_by_galaxy',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='alliance',
            name='planets_distribution_coords',
            field=models.BinaryField(null=True),
        ),
    ]
