# Generated by Django 2.2.15 on 2022-10-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0010_auto_20221002_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='members',
            field=models.ManyToManyField(related_name='ally_members', to='ogame.Player'),
        ),
    ]
