# Generated by Django 2.2.15 on 2022-10-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogame', '0013_combatreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatreport',
            name='attacker_players',
            field=models.ManyToManyField(related_name='combat_report_attacker', to='ogame.Player'),
        ),
        migrations.AddField(
            model_name='combatreport',
            name='defender_players',
            field=models.ManyToManyField(related_name='combat_report_defender', to='ogame.Player'),
        ),
    ]
