# Generated by Django 2.2.15 on 2022-10-14 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ogame', '0014_auto_20221007_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('fleet', models.BinaryField(null=True)),
                ('coord', models.CharField(blank=True, max_length=10, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_fleet_record', to='ogame.Player')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
